// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBR2TjeVAGie354WTLirmEQlhB8I5Wq9I',
    appId: '1:612000703656:web:30f3135193bc7595b54e9d',
    messagingSenderId: '612000703656',
    projectId: 'praktix-2cb43',
    authDomain: 'praktix-2cb43.firebaseapp.com',
    storageBucket: 'praktix-2cb43.firebasestorage.app',
    measurementId: 'G-S44X91S8PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ZwX6OzfHyeGCn_3nQFlB9XdfOUkR_O0',
    appId: '1:612000703656:android:6fbe3cb08d44eab9b54e9d',
    messagingSenderId: '612000703656',
    projectId: 'praktix-2cb43',
    storageBucket: 'praktix-2cb43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXQoiq1U8NLJ6Kz2MhEbRqjiC2_HiTnNs',
    appId: '1:612000703656:ios:52a91c9ece3cf31db54e9d',
    messagingSenderId: '612000703656',
    projectId: 'praktix-2cb43',
    storageBucket: 'praktix-2cb43.firebasestorage.app',
    iosBundleId: 'com.example.praktix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXQoiq1U8NLJ6Kz2MhEbRqjiC2_HiTnNs',
    appId: '1:612000703656:ios:52a91c9ece3cf31db54e9d',
    messagingSenderId: '612000703656',
    projectId: 'praktix-2cb43',
    storageBucket: 'praktix-2cb43.firebasestorage.app',
    iosBundleId: 'com.example.praktix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBR2TjeVAGie354WTLirmEQlhB8I5Wq9I',
    appId: '1:612000703656:web:ae0b7cfbcad01456b54e9d',
    messagingSenderId: '612000703656',
    projectId: 'praktix-2cb43',
    authDomain: 'praktix-2cb43.firebaseapp.com',
    storageBucket: 'praktix-2cb43.firebasestorage.app',
    measurementId: 'G-P5E1BCM1E5',
  );
}
